title:              Seems Fair
email:              napolitanobeatriceblog@gmail.com
description:        Questioning rules and decisions in human and AI systems
author:             Beatrice Napolitano
baseurl:            "/"
url:                "https://xoxor.github.io"

# Social Profiles
twitter_username:   BeaNapolitano
github_username:    xoxor
facebook_username:  
instagram_username:  
linkedin_username:   beatricenapolitano

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
